version: '3.3'
services: 
    web:
        build:
            context: .
        env_file: ./.env
        command: npm start
        volumes: 
            - .:/app/
            - /app/node_modules
        ports:
            - "30001:80"
        depends_on: 
            - mysqldb
        environment: 
            MYSQL_HOST: mysqldb
    mysqldb:
        image: mysql:5.7
        env_file: ./.env
        container_name: mysql-app
        environment: 
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        ports:
            - "30002:80"
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql

volumes:
    mysql:
    mysql_config: